// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl.menuitem'], ['zz.ui.mdl.menuitem.enums.CSS', 'zz.ui.mdl.menuitem.views.MenuItem'], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/menuitem.js', ['zz.ui.mdl.menuitem.controllers.MenuItem'], ['goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component', 'zz.ui.mdl.controllers.BaseControl', 'zz.ui.mdl.menuitem.enums.CSS', 'zz.ui.mdl.menuitem.views.MenuItem', 'zz.ui.mdl.ripple.controllers.Ripple'], false);
goog.addDependency('/../../../../../../../lib/sources/enums/css.js', ['zz.ui.mdl.menuitem.enums.CSS'], [], false);
goog.addDependency('/../../../../../../../lib/sources/views/menuitem.js', ['zz.ui.mdl.menuitem.views.MenuItem'], ['goog.dom.classlist', 'zz.ui.mdl.menuitem.enums.CSS', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/base.js', ['zz.ui.mdl.ripple'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/controllers/ripple.js', ['zz.ui.mdl.ripple.controllers.Ripple'], ['goog.Timer', 'goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component', 'zz.ui.mdl.ripple.enums.CONST', 'zz.ui.mdl.ripple.enums.CSS'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/enums/const.js', ['zz.ui.mdl.ripple.enums.CONST'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/enums/css.js', ['zz.ui.mdl.ripple.enums.CSS'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/base.js', ['zz.ui.mdl'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/controllers/basecontrol.js', ['zz.ui.mdl.controllers.BaseControl'], ['goog.events.Event', 'goog.ui.Component', 'goog.ui.Control', 'zz.i18n.services.DefaultFormatter', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/views/baseview.js', ['zz.ui.mdl.views.BaseView'], ['goog.ui.ControlRenderer', 'goog.ui.registry'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/base.js', ['zz.i18n'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/decimalformatter.js', ['zz.i18n.services.DecimalFormatter'], ['goog.i18n.NumberFormat', 'goog.i18n.NumberFormat.Format'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/defaultformatter.js', ['zz.i18n.services.DefaultFormatter'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/soymessages.js', ['zz.i18n.services.SoyMessages'], ['goog.array', 'goog.dom', 'soy'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/base.js', ['zz.models', 'zz.models.Message'], ['goog.async.run', 'zz.models.enums.EventType', 'zz.models.events.DatarowUpdate'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/enums/errortype.js', ['zz.models.enums.ErrorType'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/enums/eventtype.js', ['zz.models.enums.EventType'], ['goog.events'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/enums/fieldtypes.js', ['zz.models.enums.FieldType'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/events/datarowcreate.js', ['zz.models.events.DatarowCreate'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/events/datarowdelete.js', ['zz.models.events.DatarowDelete'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/events/datarowupdate.js', ['zz.models.events.DatarowUpdate'], ['zz.events.BaseEvent', 'zz.models.enums.EventType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/models/datarow.js', ['zz.models.Datarow'], ['goog.object', 'zz.models', 'zz.models.enums.ErrorType', 'zz.models.enums.FieldType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/lib/sources/models/dataset.js', ['zz.models.Dataset'], ['goog.array', 'goog.async.run', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.object', 'goog.pubsub.PubSub', 'zz.models', 'zz.models.Message', 'zz.models.enums.ErrorType', 'zz.models.enums.EventType', 'zz.models.events.DatarowCreate', 'zz.models.events.DatarowDelete'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/node_modules/zz.events/lib/sources/base.js', ['zz.events'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.models/node_modules/zz.events/lib/sources/events/baseevents.js', ['zz.events.BaseEvent'], [], false);
